kafka:
  enabled: ${KAFKA_ENABLED:false}
  camelEnabled: ${KAFKA_CAMEL_ENABLED:false}
  streamsEnabled: ${KAFKA_STREAMS_ENABLED:false}
  bootstrapServer: ${KAFKA_BOOTSTRAP_SERVER:localhost:9094}
  inboundTopic: ${KAFKA_INBOUND_TOPIC:test-topic}
  outboundTopic: ${KAFKA_OOUTBOUND_TOPIC:test-out-topic}
  consumerGroup: ${KAFKA_CONSUMER_GROUP:test-consumergroup-1}

rabbitmq:
  server:
    hostname: ${RABBITMQ_SERVER_HOSTNAME:localhost}
    port: ${RABBITMQ_SERVER_PORT:9095}
  msq:
    enabled: ${RABBITMQ_MSQ_ENABLED:false}
    inboundQueue: ${RABBITMQ_MSQ_INBOUND_QUEUE:test-queue-1}
    persistentMessages: ${RABBITMQ_MSQ_PERSISTENT_MESSAGES:false}
    exclusiveQueue: ${RABBITMQ_MSQ_EXCLUSIVE_QUEUE:false}
  pubsub:
    enabled: ${RABBITMQ_PUBSUB_ENABLED:false}
    bindingKey: ${RABBITMQ_PUBSUB_BINDING_KEY:#}
    exchangeName: ${RABBITMQ_PUBSUB_EXCHANGE_NAME:test-topic-1}
    queuePrefix: ${RABBITMQ_PUBSUB_QUEUE_PREFIX:bound-}
    namedQueue: ${RABBITMQ_PUBSUB_NAMED_QUEUE:false}
    persistentMessages: ${RABBITMQ_PUBSUB_PERSISTENT_MESSAGES:false}
    exclusiveQueue: ${RABBITMQ_PUBSUB_EXCLUSIVE_QUEUE:false}

rocketmq:
  enabled: ${ROCKETMQ_ENABLED:false}
  nameserver: ${ROCKETMQ_NAMESERVER:localhost:9096}
  groupName: ${ROCKETMQ_GROUP_NAME:rocket-consumer-group-1}
  inboundTopic: ${ROCKETMQ_INBOUND_TOPIC:test-queue-1}

activemq:
  enabled: ${ACTIVEMQ_ENABLED:false}
  server: ${ACTIVEMQ_SERVER:localhost:9101}
  inboundQueue: ${ACTIVEMQ_INBOUND_QUEUE:test-queue-1}

nsq:
  enabled: ${NSQ_ENABLED:false}
  server: ${NSQ_SERVER:localhost:9105}
  consumerCount: ${NSQ_CONSUMER_COUNT:1}
  inboundTopic: ${NSQ_INBOUND_TOPIC:test-topic-1}
  channel: ${NSQ_CHANNEL:test-channel-1}

sqs:
  enabled: ${SQS_ENABLED:false}
  queueName: ${SQS_QUEUE_NAME:test-s24067-sqs-standard}
  region: ${SQS_REGION:eu-central-1}
  accessKeyId: ${SQS_ACCESS_KEY_ID}
  accessKeySecret: ${SQS_ACCESS_KEY_SECRET}
  consumerCount: ${SQS_CONSUMER_COUNT:1}